apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    name: prod
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "node-type=production"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
---
# OPA Gatekeeper Policy for Image Security
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: requiredimagesources
  annotations:
    metadata.gatekeeper.sh/title: "Required Image Sources"
    metadata.gatekeeper.sh/version: 1.0.0
    description: "Requires container images to come from approved registries"
spec:
  crd:
    spec:
      names:
        kind: RequiredImageSources
      validation:
        type: object
        properties:
          allowedRegistries:
            type: array
            description: "List of allowed registries"
            items:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requiredimagesources
        
        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not starts_with(container.image, input.parameters.allowedRegistries[_])
          msg := sprintf("Container image '%v' is not from an allowed registry", [container.image])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredImageSources
metadata:
  name: must-come-from-approved-registries
  namespace: prod
spec:
  match:
    kinds:
      - apiGroups: ["apps", ""]
        kinds: ["Deployment", "Pod", "ReplicaSet"]
    namespaces: ["prod"]
  parameters:
    allowedRegistries:
      - "ghcr.io/mankinimbom/"
      - "gcr.io/distroless/"
      - "registry.k8s.io/"
