apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argocd-apps
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- namespace.yaml
- secrets.yaml
- backend.yaml
- frontend.yaml

commonLabels:
  environment: production
  managed-by: argocd

namespace: argocd
