apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-secrets
  namespace: argocd
  labels:
    app: secrets
    environment: production
    component: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: prod
  source:
    repoURL: https://github.com/mankinimbom/prod-gitops.git
    targetRevision: main
    path: secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
