apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: image-updater
data:
  log.level: info
  applications: |
    - name: prod-backend
      image-list:
        - name: backend
          image: ghcr.io/mankinimbom/backend
          platforms: linux/amd64
          update-strategy: semver
          semver-constraint: ">=1.0.0 <2.0.0"
          allow-tags: ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$
          ignore-tags: ^.*-(rc|alpha|beta).*$
      write-back-method: git
      git-branch: image-updates
      git-commit-user: argocd-image-updater[bot]
      git-commit-email: argocd-image-updater@noreply.github.com
      git-commit-message: "chore(backend): update image to {{.NewTag}} [skip ci]"
      git-commit-sign-off: true
    - name: prod-frontend
      image-list:
        - name: frontend
          image: ghcr.io/mankinimbom/frontend
          platforms: linux/amd64
          update-strategy: semver
          semver-constraint: ">=1.0.0 <2.0.0"
          allow-tags: ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$
          ignore-tags: ^.*-(rc|alpha|beta).*$
      write-back-method: git
      git-branch: image-updates
      git-commit-user: argocd-image-updater[bot]
      git-commit-email: argocd-image-updater@noreply.github.com
      git-commit-message: "chore(frontend): update image to {{.NewTag}} [skip ci]"
      git-commit-sign-off: true
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io/v2
      credentials: secret:argocd/github-registry-creds#token
      default: true
      insecure: false
      tagSortMode: semver
      defaultNS: mankinimbom
