name: Backend CI/CD
on:
  push:
    branches: [main]
    paths:
    - 'apps/backend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
      working-directory: apps/backend
    - run: npm test
      working-directory: apps/backend
    - run: docker build -t ghcr.io/mankinimbom/backend:1.0.0 apps/backend
    - run: echo "$CR_PAT" | docker login ghcr.io -u mankinimbom --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    - run: docker push ghcr.io/mankinimbom/backend:1.0.0
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ArgoCD Sync Backend
      uses: argoproj/argocd-action@v2
      with:
        argocd_version: v2.10.7
        command: app sync
        appName: backend
        username: ${{ secrets.ARGOCD_USERNAME }}
        password: ${{ secrets.ARGOCD_PASSWORD }}
        server: ${{ secrets.ARGOCD_SERVER }}
