apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prod-secrets
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- backend-secrets.yaml

commonLabels:
  environment: production
  managed-by: argocd

namespace: prod
